version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade --user awscli
      - npm install
      - chmod u+x ./build/read-environment.sh
      - chmod u+x ./build/build.sh
      - chmod u+x ./build/deploy.sh
  build:
    commands:
      - sh ./build/build.sh
      - sh ./build/deploy.sh
